version: '3.8'
services:
  frontend:
    image: docker.io/tumachieu/frontend:{{IMAGE_TAG}}
    ports:
      - "8080:8080"
    environment:
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070
      - RECOMMENDATION_SERVICE_ADDR=recommendationservice:8080
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - CHECKOUT_SERVICE_ADDR=checkoutservice:5050
      - AD_SERVICE_ADDR=adservice:9555
  #cartservice:
   # image: docker.io/tumachieu/cartservice:{{IMAGE_TAG}}
   # ports:
    #  - "7070:7070"
 # productcatalogservice:
 #   image: docker.io/tumachieu/productcatalogservice:{{IMAGE_TAG}}
 #   ports:
  #    - "3550:3550"